@Test
public void T2_04_load_profile_switch_profiles() throws Exception {
    runCommands(unpack(CREATE_SOME_CLIENTS, LOAD_PROFILE, "tom", LOAD_PROFILE, "jenny", PRINT_DB));
    assertContains("Profile loaded for Tom.");
    assertContains("Profile loaded for Jenny.");
    assertContains("Database has 3 profiles:");
    assertContains("1: Jordan, 21");
    assertContains("2: Tom, 25");
    assertContains("*** 3: Jenny, 23");
    assertDoesNotContain("*** 1: Jordan, 21", true);
    assertDoesNotContain("*** 2: Tom, 25", true);
}
java.lang.AssertionError: 
The test is expecting the following output in the console, but it was not there: 
	"*** 3: Jenny, 23"
	at nz.ac.auckland.se281.MainTest$Task2.T2_04_load_profile_switch_profiles(MainTest.java:125)

@Test
public void T2_03_load_profile_found_display() throws Exception {
    runCommands(unpack(CREATE_SOME_CLIENTS, LOAD_PROFILE, "Tom", PRINT_DB));
    assertContains("Profile loaded for Tom.");
    assertContains("Database has 3 profiles:");
    assertContains("1: Jordan, 21");
    assertContains("*** 2: Tom, 25");
    assertContains("3: Jenny, 23");
}
java.lang.AssertionError: 
The test is expecting the following output in the console, but it was not there: 
	"*** 2: Tom, 25"
	at nz.ac.auckland.se281.MainTest$Task2.T2_03_load_profile_found_display(MainTest.java:110)

@Test
public void T2_xx_cannot_create_profile_while_loaded() throws Exception {
    runCommands(unpack(CREATE_SOME_CLIENTS, LOAD_PROFILE, "TOM", CREATE_PROFILE, "Who", 19, PRINT_DB));
    assertContains("1: Jordan, 21");
    assertContains("*** 2: Tom, 25");
    assertContains("3: Jenny, 23");
    assertContains("Cannot create a new profile. First unload the profile for Tom.");
    assertDoesNotContain("*** 1: Jordan, 21", true);
    assertDoesNotContain("*** 3: Jenny, 23", true);
    assertDoesNotContain("Who, 19", true);
}
java.lang.AssertionError: 
The test is expecting the following output in the console, but it was not there: 
	"*** 2: Tom, 25"
	at nz.ac.auckland.se281.MainTest$Task2.T2_xx_cannot_create_profile_while_loaded(MainTest.java:373)

@Test
public void T2_xx_load_profile_found_ignore_case_display() throws Exception {
    runCommands(unpack(CREATE_SOME_CLIENTS, LOAD_PROFILE, "tom", PRINT_DB));
    assertContains("Profile loaded for Tom.");
    assertContains("Database has 3 profiles:");
    assertContains("1: Jordan, 21");
    assertContains("*** 2: Tom, 25");
    assertContains("3: Jenny, 23");
}
java.lang.AssertionError: 
The test is expecting the following output in the console, but it was not there: 
	"*** 2: Tom, 25"
	at nz.ac.auckland.se281.MainTest$Task2.T2_xx_load_profile_found_ignore_case_display(MainTest.java:267)

@Test
public void T2_xx_load_profile_found_display() throws Exception {
    runCommands(unpack(CREATE_SOME_CLIENTS, LOAD_PROFILE, "Tom", PRINT_DB));
    assertContains("Profile loaded for Tom.");
    assertContains("Database has 3 profiles:");
    assertContains("1: Jordan, 21");
    assertContains("*** 2: Tom, 25");
    assertContains("3: Jenny, 23");
}
java.lang.AssertionError: 
The test is expecting the following output in the console, but it was not there: 
	"*** 2: Tom, 25"
	at nz.ac.auckland.se281.MainTest$Task2.T2_xx_load_profile_found_display(MainTest.java:230)

@Test
public void T2_xx_load_profile_ignore_invalid_switch() throws Exception {
    runCommands(unpack(CREATE_SOME_CLIENTS, LOAD_PROFILE, "jordan", LOAD_PROFILE, "unknown", PRINT_DB));
    assertContains("Profile loaded for Jordan.");
    assertContains("No profile found for Unknown. Profile not loaded.");
    assertContains("Database has 3 profiles:");
    assertContains("*** 1: Jordan, 21");
    assertContains("2: Tom, 25");
    assertContains("3: Jenny, 23");
    assertDoesNotContain("Profile loaded for unknown", true);
    assertDoesNotContain("*** 2: Tom, 25", true);
    assertDoesNotContain("*** 3: Jenny, 23", true);
}
java.lang.AssertionError: 
The test is expecting the following output in the console, but it was not there: 
	"No profile found for Unknown. Profile not loaded."
	at nz.ac.auckland.se281.MainTest$Task2.T2_xx_load_profile_ignore_invalid_switch(MainTest.java:305)

@Test
public void T2_xx_load_profile_switch_profiles() throws Exception {
    runCommands(unpack(CREATE_SOME_CLIENTS, LOAD_PROFILE, "tom", LOAD_PROFILE, "jenny", PRINT_DB));
    assertContains("Profile loaded for Tom.");
    assertContains("Profile loaded for Jenny.");
    assertContains("Database has 3 profiles:");
    assertContains("1: Jordan, 21");
    assertContains("2: Tom, 25");
    assertContains("*** 3: Jenny, 23");
    assertDoesNotContain("*** 1: Jordan, 21", true);
    assertDoesNotContain("*** 2: Tom, 25", true);
}
java.lang.AssertionError: 
The test is expecting the following output in the console, but it was not there: 
	"*** 3: Jenny, 23"
	at nz.ac.auckland.se281.MainTest$Task2.T2_xx_load_profile_switch_profiles(MainTest.java:288)

@Test
public void T2_xx_delete_profile_not_found() throws Exception {
    runCommands(unpack(CREATE_SOME_CLIENTS, DELETE_PROFILE, "alex", PRINT_DB));
    assertDoesNotContain("Profile deleted for Alex", true);
    assertContains("No profile found for Alex. No profile was deleted.");
    assertContains("Database has 3 profiles:");
    assertContains("1: Jordan, 21");
    assertContains("2: Tom, 25");
    assertContains("3: Jenny, 23");
}
java.lang.AssertionError: 
The test is expecting the following output in the console, but it was not there: 
	"No profile found for Alex. No profile was deleted."
	at nz.ac.auckland.se281.MainTest$Task2.T2_xx_delete_profile_not_found(MainTest.java:434)

